### ISSUE TITLE
Zoeken in Geopunt catalogus werkt niet meer

### ISSUE THREAD

**Issue by wdlb** [Informatievlaanderen/geopunt-plugins-qgis#1]
Bij het zoeken in de Geopunt-catalogus krijg ik steeds "Aantal gevonden: 0" / "Warning: No results were found", onafhankelijk van de zoekterm/filters op Organisation/Type.

![image](https://github.com/Informatievlaanderen/geopunt-plugins-qgis/assets/3765473/bebc5885-9926-4abb-9103-0b77c709c82d)

Mocht je wat meer info/context/hulp bij het testen/ ... nodig hebben, ik help graag.

versie QGIS: 3.34.4
versie geopunt4Qgis: 2.3.0.5

**Comment by jbostoen** [comment]
Zelfde issue vastgesteld.

**Comment by rodjur** [comment]
same problem

**Comment by wdlb** [comment]
En ik kan bevestigen dat met de update naar de laatste versie 2.4.0.0 alles weer werkt zoals verwacht. Dankjewel!
