### ISSUE TITLE
Zoeken op adres lukt niet meer

### ISSUE THREAD

**Issue by filipmahieu** [Informatievlaanderen/geopunt-plugins-qgis#2]
Zoeken op adres: python-error (sinds nieuwe update denk ik)

**Comment by Stroomtang** [comment]
De service die hiervoor wordt gebruikt (api.basisregisters.vlaanderen.be) heeft hun 'V1' hiervan uitgeschakeld waardoor je geen gemeentes meer kan opvragen. Dit moet geupdate worden naar V2, ik heb hiervoor net een pull request gemaakt: https://github.com/Informatievlaanderen/geopunt-plugins-qgis/pull/3

**Comment by tom-van-haute** [comment]
fixed in qgis3-bracnh
